#!/usr/bin/env python3

from __future__ import annotations

import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

logging.basicConfig(
    level=logging.INFO, format="%(levelname)-8s %(message)s", stream=sys.stdout
)
log = logging.getLogger(__name__)

SERVICES: dict[str, str] = {
    "Build service": "https://build.openpak.org",
    "Main repository server": "https://hub.openpak.org/status",
    "Website": "https://openpak.org",
    "API": "https://openpak.org/api/v2/status",
    "CDN": "https://dl.openpak.org/repo/logo.svg",
}

GITHUB_STATUS_URL = "https://www.githubstatus.com/api/v2/status.json"
GITHUB_NOTICE_FILE = Path("content/issues/github-notice.md")
GITHUB_WARN_INDICATORS = {"minor", "major", "critical"}

CONSECUTIVE_THRESHOLD = 2
STATE_FILE = Path(".github/uptime-state.json")
ISSUES_DIR = Path("content/issues")
FILE_PREFIX = "service-down-"


def has_unresolved_manual_issue() -> bool:
    if not ISSUES_DIR.exists():
        return False

    for path in ISSUES_DIR.glob("*.md"):
        if path.name.startswith(FILE_PREFIX) or path.name.endswith("github-notice.md"):
            continue

        if re.search(r"^resolved:\s*false\s*$", path.read_text(), flags=re.MULTILINE):
            log.warning("Skipping as manual unresolved incident open: %s", path)
            return True

    return False


def file_name(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def check_service(url: str) -> tuple[bool, int, str | None]:
    try:
        r = requests.get(url, timeout=10, allow_redirects=True)
        return r.status_code < 500 and r.status_code != 404, r.status_code, None
    except requests.RequestException as err:
        cause = err.__cause__ or err
        return False, 0, str(cause)


def check_github_status() -> tuple[str, str]:
    try:
        r = requests.get(GITHUB_STATUS_URL, timeout=10)
        data = r.json()
        indicator = data["status"]["indicator"]
        description = data["status"]["description"]
        return indicator, description
    except Exception as err:
        log.error("Failed to fetch GitHub status: %s", err)
        return "none", "All Systems Operational"


def write_github_notice(date: str, description: str) -> None:
    ISSUES_DIR.mkdir(parents=True, exist_ok=True)

    existing_date = None

    if GITHUB_NOTICE_FILE.exists():
        match = re.search(
            r"^date:\s*(.+?)\s*$",
            GITHUB_NOTICE_FILE.read_text(),
            flags=re.MULTILINE,
        )
        if match:
            existing_date = match.group(1).strip()

    final_date = existing_date or date

    content = (
        "---\n"
        "title: GitHub is experiencing issues\n"
        f"date: {final_date}\n"
        "severity: disrupted\n"
        "resolved: false\n"
        'resolvedWhen: ""\n'
        "pin: false\n"
        "section: issue\n"
        "\n"
        "affected:\n"
        "  - Build service\n"
        "\n"
        "# This is an autogenerated issue report and it will be automatically\n"
        "# deleted when all services are up. Please do not edit this.\n"
        "# A manual incident report with 'resolved' set to 'false' will disable\n"
        "# automatic incident reporting until the incident is resolved.\n"
        "---\n"
        "\n"
        "Please follow https://www.githubstatus.com\n"
        "\n"
    )

    GITHUB_NOTICE_FILE.write_text(content)
    log.info("Wrote GitHub notice: %s", GITHUB_NOTICE_FILE)


def delete_github_notice() -> None:
    if GITHUB_NOTICE_FILE.exists():
        GITHUB_NOTICE_FILE.unlink()
        log.info("Deleted GitHub notice: %s", GITHUB_NOTICE_FILE)


def load_state() -> dict[str, int]:
    state: dict[str, int] = {}

    if STATE_FILE.exists():
        try:
            state = json.loads(STATE_FILE.read_text())
        except (json.JSONDecodeError, OSError) as err:
            log.error("Failed to read state file: %s", err)
            state = {}

    return state


def save_state(state: dict[str, int]) -> None:
    try:
        STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        STATE_FILE.write_text(json.dumps(state, indent=2))
    except OSError as err:
        log.error("Failed to write state file: %s", err)


def issue_path(name: str) -> Path:
    return ISSUES_DIR / f"{FILE_PREFIX}{file_name(name)}.md"


def cstate_content(title: str, date: str, affected: list[str]) -> str:
    affected_lines = "\n".join(f"  - {a}" for a in affected)

    return (
        "---\n"
        f"title: {title}\n"
        f"date: {date}\n"
        "severity: down\n"
        "resolved: false\n"
        'resolvedWhen: ""\n'
        "pin: true\n"
        "section: issue\n"
        "\n"
        "affected:\n"
        f"{affected_lines}\n"
        "\n"
        "# This is an autogenerated issue report and it will be automatically\n"
        "# deleted when all services are up. Please do not edit this.\n"
        "# A manual incident report with 'resolved' set to 'false' will disable\n"
        "# automatic incident reporting until the incident is resolved.\n"
        "---\n"
    )


def write_issue(path: Path, title: str, date: str, affected: list[str]) -> None:
    ISSUES_DIR.mkdir(parents=True, exist_ok=True)

    existing_date = None

    if path.exists():
        match = re.search(
            r"^date:\s*(.+?)\s*$",
            path.read_text(),
            flags=re.MULTILINE,
        )

        if match:
            existing_date = match.group(1).strip()

    final_date = existing_date or date

    path.write_text(cstate_content(title, final_date, affected))
    log.info("Wrote issue: %s", path)


def delete_issue(path: Path) -> None:
    if path.exists():
        path.unlink()
        log.info("Deleted issue: %s", path)


def main() -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

    if has_unresolved_manual_issue():
        return

    gh_indicator, gh_description = check_github_status()
    log.info("GitHub status: %s — %s", gh_indicator, gh_description)

    if gh_indicator in GITHUB_WARN_INDICATORS:
        write_github_notice(now, gh_description)
    else:
        delete_github_notice()

    results: dict[str, tuple[bool, int]] = {}

    for name, url in SERVICES.items():
        up, code, err = check_service(url)

        log.info("%-6s [%3s]  %s", "UP" if up else "DOWN", code, name)

        if err:
            log.error("       %s", err)

        results[name] = (up, code)

    down_now = {n for n, (up, _) in results.items() if not up}
    up_now = {n for n, (up, _) in results.items() if up}

    state: dict[str, int] = load_state()

    for name in down_now:
        state[name] = state.get(name, 0) + 1

    for name in up_now:
        if state.pop(name, 0) >= CONSECUTIVE_THRESHOLD:
            log.info("%s has recovered", name)

    triggered = [n for n in down_now if state.get(n, 0) >= CONSECUTIVE_THRESHOLD]

    combined = ISSUES_DIR / f"{FILE_PREFIX}multiple-services.md"

    if len(triggered) == 0:
        delete_issue(combined)

        for name in SERVICES:
            delete_issue(issue_path(name))

    elif len(triggered) == 1:
        delete_issue(combined)

        name = triggered[0]
        path = issue_path(name)

        write_issue(path, f"{name} is down", now, [name])

    else:
        for name in SERVICES:
            delete_issue(issue_path(name))

        write_issue(combined, "Multiple services down", now, sorted(triggered))

    save_state(state)


if __name__ == "__main__":
    main()
